Repository bauripalash/quotebox, pull requests merged in 2019-10, with the labels that each got.

#15 Add a quote by Stephen Hawking
  quotes.json
Labels: Fix-Conflicts, No-comma

#16 Mises's Quote
  quotes.json
Labels: Fix-Conflicts, No-comma

#33 Added quote by Grace Hopper
  quotes.json
Labels: Fix-Conflicts, No-comma

#58 New Quote Added
  quotes.json
Labels: Unnecessary-Comma

#13 Added quote from Maya Angelou
  quotes.json
Labels: Fix-Conflicts

#54 Added Quote by Lord Acton
  quotes.json
Labels: Quote-Elements-Must-Be-Inside

#62 add quote
  quotes.json
Labels: Another-Language, No-comma
